spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.50.103:3316/vcard_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: user_fucent
    password: fucent
